# External gems
# See http://ixti.net/software/2013/01/28/using-jekyll-plugins-on-github-pages.html for making `jekyll archives` work.
gems:
  - jekyll-archives # Sorry, not GitHub pages friendly!
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-toc

exclude: [vendor, README.md, LICENSE.md, Gemfile, Gemfile.lock, circle.yml]

keep_files: [.htaccess, files]


# Site settings
# title: "에듀롬"
title: "에듀롬 @ KISTI"
subtitle: "한국과학기술정보연구원 에듀롬 서비스 안내"
# email: eduroam@kreonet.kr
name: "KISTI 에듀롬담당자"
description: "한국과학기술정보연구원 에듀롬 서비스 안내"
copyright: © 1988 - KISTI
copyright_detail: >
  <a href="http://www.kisti.re.kr">한국과학기술정보연구원</a>은 
  <a href="http://eduroam.kreonet.kr">에듀롬(한국)</a>과의 협력을 통해 
  본 연구원에서 에듀롬 서비스를 제공합니다.<br />
  대학생과 연구자를 위한 글로벌 Wi-Fi 로밍 서비스인 에듀롬은 
  <a href="http://www.msip.go.kr">과학기술정보통신부</a>가 지원하고 
  <a href="http://www.kisti.re.kr">한국과학기술정보연구원</a>이 관리하는 
  <a href="http://www.kreonet.net">국가과학기술연구망</a>에서 운영합니다.


menu:
  - title: "협력기관"
    url: "http://eduroam.kreonet.kr/collabo/"
  - title: "기반기술"
    url: "http://eduroam.kreonet.kr/tech/"

# Base URL of site (i.e. /blog). It should always start with a slash,
# and never end with a slash. Set it to a blank value if hosting at the
# root of your server.
baseurl: "/sample" # the subpath of your site, e.g. /blog/
url: "http://eduroam.kreonet.kr/sample" # the base hostname & protocol for your site
cover: "/assets/covers/kisti.jpg"
logo: "/assets/logo.png"
logo2: "/assets/logo_kisti.png"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: false
highlightjs_theme: "monokai-sublime"

# Archive settings (see https://github.com/jekyll/jekyll-archives/)
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: 'archive'
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'

# Disqus comments
# disqus_shortname: bencentra

# Google analytics
# ga_tracking_id: "UA-XXXX-1"

# Category descriptions (for archive pages)
descriptions:
  - cat: jekyll
    desc: "Posts describing Jekyll setup techniques."

  - cat: dummy
    desc: "Just some placeholder posts, lorem ipsum and the rest."

# Social icons and sharing options
#
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets
#
# Example:
#
# social:
#   - name: Twitter                         # Name of the service
#     icon: twitter                         # Font Awesome icon to use (minus fa- prefix)
#     username: "@TheBenCentra"             # (User) Name to display in the footer link
#     url: https://twitter.com/TheBenCentra # URL of your profile (leave blank to not display in footer)
#     desc: Follow me on Twitter            # Description to display as link title, etc
#     share: true                           # Include in the "Share" section of posts
social:
  - name: "에듀롬(한국) 홈페이지"
    icon: home
    url: http://eduroam.kreonet.kr
    desc:
    share: true

  - name: "에듀롬(한국) 교육부문 홈페이지"
    icon: home
    url: http://www.eduroam.kr
    desc:
    share: true

  - name: "에듀롬 글로벌 홈페이지"
    icon: home
    url: https://www.eduroam.org
    desc:
    share: true

  - name: Facebook
    icon: facebook
    username: 에듀롬 페이스북 (한국)
    url: https://facebook.com/eduroamkr
    desc:
    share: true


en:
  title: "eduroam @ KISTI"
  subtitle: "eduroam Service Information at KISTI"
  # email: eduroam@kreonet.kr
  name: KISTI eduroam manager
  description: eduroam Service Information at KISTI
  copyright: © 1988 - KISTI
  copyright_detail: >
    eduroam is served on <a href="http://www.kisti.re.kr/eng/">KISTI</a> 
    in collaboration with 
    <a href="http://www.kisti.re.kr/eng/">KISTI</a> and 
    <a href="http://eduroam.kreonet.kr">eduroam Korea</a>.<br />
    <a href="http://eduroam.kreonet.kr">eduroam Korea</a> 
    is operated by <a href="http://www.kreonet.net">KREONET</a>, 
    which managed by <a href="http://www.kisti.re.kr/eng/">KISTI</a>, 
    and funded by <a href="http://english.msip.go.kr">MISP</a>.

  menu:
    - title: "Collabo"
      url: "http://eduroam.kreonet.kr/en/collabo/"
    - title: "Technology"
      url: "http://eduroam.kreonet.kr/en/tech/"

  social:
    - name: "eduroam Korea"
      icon: home
      url: http://eduroam.kreonet.net/en/
      desc:
      share: true

    - name: "eduroam Global"
      icon: home
      url: https://www.eduroam.org
      desc:
      share: true

    - name: "eduroam Korea edu-part"
      icon: home
      url: http://www.eduroam.kr
      desc:
      share: true

    - name: Facebook
      icon: facebook
      username: eduroam Korea Facebook
      url: https://facebook.com/eduroamkr
      desc:
      share: true



# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
protocols:
    fb_image: "/assets/logo.png"
    fb_image_width: 612
    fb_image_height: 605
    fb_image_type: "image/png"

    twitter_image: "/assets/logo.png"

    os_repo: "https://github.com/bencentra/centrarium.com"
    os_rcs_type: "git"
    os_src: "git@github.com:bencentra/centrarium.com.git"
